version: '3.8'

services:
    pihole:
        image: pihole/pihole:latest
        container_name: pihole
        restart: unless-stopped
        network_mode: "host"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "80:80/tcp"
            - "443:443/tcp"
        environment:
            # You may have to change the server-IP / DNS servers.
            ServerIP: 192.168.1.254
            DNS1: 1.1.1.1
            DNS2: 1.0.0.1
            DNSMASQ_LISTENING: all
            TZ: 'Europe/Berlin'
        env_file: 
            - .env
        volumes:
            - pihole-data:/etc/pihole/
            - pihole-dnsmasq:/etc/dnsmasq.d/
        dns:
            - 127.0.0.1
        cap_add:
            - NET_ADMIN

volumes: 
    pihole-data:
    pihole-dnsmasq: