version: '3.8'

services: 
    grafana:
        image: grafana:latest
        container_name: grafana
        restart: unless-stopped
        ports:
            - 3000:3000
        volumes: 
            - grafana-data:/var/lib/grafana
            - ${PWD}/import_dashboard.yml:/etc/grafana/provisioning/dashboards/import_dashboard.yml:ro
            - ${PWD}/dashboards:/var/lib/grafana/dashboards:ro
            - ${PWD}/datasources:/etc/grafana/provisioning/datasources:ro
        env_file: 
            - .env

volumes: 
    grafana-data:

networks: 
    default:
        external: 
            name: node-red-net