version: '3.8'

services: 
    jupiter:
        image: jupyter/tensorflow-notebook
        container_name: jupyter
        restart: unless-stopped
        ports: 
            - 8888:8888
        environment: 
            - JUPYTER_ENABLE_LAB=yes
        volumes: 
            - jupyter:/home/jovyan/work

volumes: 
    jupyter: