version: '3.8'

services: 
    app:
        image: wordpress:latest
        container_name: Wordpress
        restart: unless-stopped
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        environment: 
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_HOST: database:3306
        volumes:
            - wordpress:/var/www/html
        depends_on:
            - database
    
    database:
        image: mariadb
        container_name: database
        restart: unless-stopped
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            # Uncomment / Comment below if somewthing went wrong
            #MYSQL_INITDB_SKIP_TZINFO: 1
        volumes: 
            - database:/var/lib/mysql

volumes: 
    wordpress:
    database: