version: "3.8"

services: 
    node-red:
        image: nodered/node-red:latest
        container_name: node-red
        restart: always
        environment: 
            - TZ=Europe/Berlin
        ports: 
            - 1880:1880
        networks: 
            - node-red-net
        volumes: 
            - node-red-data:/data

volumes: 
    node-red-data:

networks: 
    node-red-net: