version: "3.8"

services: 
    influxdb:
        build: .
        container_name: influxdb
        restart: unless-stopped
        ports: 
            - 8086:8086/tcp
        volumes: 
            - influxdb-data:/var/lib/influxdb
        command: -config /etc/influxdb/influxdb.conf
        environment:
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
            - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
            - INFLUXDB_USER=${INFLUXDB_USER}
            - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
            - INFLUXDB_DB=${INFLUXDB_DB}

volumes: 
    influxdb-data: